#!/bin/sh -e

# create the log directory if it doesn't exist
mkdir -p /var/log/runit/fpm

# tell svlogd to drop the stdout into our custom location
cd /var/log/runit/fpm
exec svlogd -v -ttt /var/log/runit/fpm
