#!/bin/sh -e

# create the log directory if it doesn't exist
mkdir -p /var/log/runit/nginx

# tell svlogd to drop the stdout into our custom location
cd /var/log/runit/nginx
exec svlogd -v -ttt /var/log/runit/nginx
